apiVersion: v1
kind: Secret
metadata:
  name: app-env
type: Opaque
stringData:
  DB_URI: mongodb://appuser:${MONGO_APP_PASS}@mongo-mongodb.app.svc.cluster.local:27017/blogger?authSource=admin
  JWT_SECRET: ${JWT_SECRET}
