apiVersion: v1
kind: Secret
metadata:
  name: app-env
type: Opaque
stringData:
  MONGODB_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo.${NAMESPACE}.svc.cluster.local:27017/${MONGO_DB}?authSource=admin
  JWT_SECRET: ${JWT_SECRET}
