name: build-dockerhub
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        default: 'wesleymessiassilva91/desafio-devsecops'
      context:
        type: string
        default: '.'
      dockerfile:
        type: string
        default: 'Dockerfile'
      push_latest:
        type: boolean
        default: true
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      - name: Build & Push (sha + latest)
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file:    ${{ inputs.dockerfile }}
          push:    true
          tags: |
            ${{ secrets.dockerhub_username }}/desafio-devsecops:${{ github.sha }}
            ${{ secrets.dockerhub_username }}/desafio-devsecops:latest
          provenance: false