name: build-dockerhub
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        default: 'wesleymessiassilva91/desafio-devsecops'
      context:
        type: string
        default: '.'
      dockerfile:
        type: string
        default: 'Dockerfile'
      push_latest:
        type: boolean
        default: true
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.meta.outputs.image_sha }}
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      - name: Compute image tags
        id: meta
        run: |
          IMAGE_NAME="wesleymessiassilva91/desafio-devsecops"
          echo "image_sha=${IMAGE_NAME}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          {
            echo 'tags<<EOF'
            echo "${IMAGE_NAME}:${GITHUB_SHA}"
            if [[ "${{ inputs.push_latest }}" == "true" ]]; then
              echo "${IMAGE_NAME}:latest"
            fi
            echo 'EOF'
          } >> "$GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
